version: "3.4"

services:
#####################
# BE
#####################
  be-challenge:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80" # port of to where localstack can be addressed to
  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
      - 80:80
      - 5341:5341
    environment:
      - ACCEPT_EULA=Y # a list of desired services you want to use.
      # - SEQ_FIRSTRUN_ADMINPASSWORDHASH="$PH"
    volumes:
      - "./docker-data/seq:/data"